name: deploy2

on:
  workflow_dispatch:
    inputs:
      name:
        description: name of the runner
        required: true
      name2:
        description: optional
        required: false

jobs:
  testing2:
    runs-on: ubuntu-latest
    steps:
      - name: print test2
        run: echo "test2"
      - name: shell commands
        run: |
          node -v
          npm -v
