name: deploy2

on:
  workflow_dispatch:
    inputs:
      name:
        description: name of the runner venkat
        required: true
        default: "venkat"
      name2:
        description: optional
        required: false
        default: "na"

jobs:
  testing2:
    runs-on: ubuntu-la
    steps:
      - name: print test2
        run: echo "test2"
      - name: shell commands
        run: |
          node -v
          npm -v
